<div class="login-box">
    <div class="login-logo">
        <a href="/"><b>Admin</b>LTE</a>
    </div><!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg"><?php echo $this->message ?></p>

        <?php if($this->form): ?>
            <form action="<?php echo $this->url('account/forgot'); ?>" method="post">
                <div class="form-group has-feedback">
                    <input type="email" class="form-control" placeholder="Email" name="email">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <hr>
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" placeholder="Enter Secret" name="secret">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="New Password" name="password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="Confirm New Password" name="confirm_password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                    </div><!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Change</button>
                    </div><!-- /.col -->
                </div>
            </form>
        <?php endif; ?>

        <hr>

        <a href="<?php echo $this->url('account'); ?>">Back to login</a><br>

    </div><!-- /.login-box-body -->
</div><!-- /.login-box -->